### PR TITLE
Added UI of student dashboard and updated splash screen

### PR DESCRIPTION
**Pull request by raunakraj195145**
Added UI of student dashboard and updated splash screen

### CODE REVIEW

**Review by DeepAnsh210 — CHANGES_REQUESTED** [review]
Nice
Can you improve scrolling, it is not scrolling smoothly?
I think due to high quality image.

**Review by SandeepMazumdar — APPROVED** [review]

**Review by DeepAnsh210 — APPROVED** [review]
Nice.

**Comment by raunakraj195145** [comment]
> Nice
> Can you improve scrolling, it is not scrolling smoothly?
> I think due to high quality image.

Okay

**Review by itsparthchow — COMMENTED** [review]
fantastic

**Review by itsparthchow — COMMENTED** [review]
nice

**Review by itsparthchow — APPROVED** [review]

**Pull request merged**
